source 'http://rubygems.org'

gem 'rails', '4.2.0'
gem 'rails-api'

gem 'pg', :group => :production

#auth
gem 'bcrypt'
gem 'jwt'
gem 'rack-cors'

group :development do
  gem 'sqlite3'
  gem 'spring'
end

#tz info on windows
gem 'tzinfo-data', :platforms => [:mingw, :mswin, :x64_mingw]


# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
